//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Excel_App.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SCImport
    {
        public int SCImportID { get; set; }
        public string RelateIPAddress { get; set; }
        public string RelatedNode { get; set; }
        public int ProbeID { get; set; }
        public string Job { get; set; }
        public string CIType { get; set; }
        public Nullable<System.DateTime> TimeErrorReported { get; set; }
        public string Severity { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<int> Count { get; set; }
        public string ErrorSummary { get; set; }
        public Nullable<System.DateTime> LastTimeActive { get; set; }
    
        public virtual Probe Probe { get; set; }
    }
}
